[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vignesh7778", email = "vigneshdevi22@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=2",
    "requests>=2.34.2",
]

[project.scripts]
mcp-server = "mcp_server:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
